# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '8th-Seminar' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
	pod 'lottie-ios'
  # Pods for 8th-Seminar

end
